### ISSUE TITLE
add in unit tests

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#23]
our testing of the current version of main only uses integration tests. add unit tests as needed.

**Comment by kmdeck** [comment]
A couple of things...

Do we want to support a model with no prognostic variables? In component form, maybe so. In standalone, no - I think we'd get errors for ODE.jl if Y was empty.


noticing in Code cov that in model.jl we do not ever test:
```
prognostic_vars(m::AbstractModel) = ()
```
```
function make_rhs(model::AbstractModel)
    function rhs!(dY, Y, p, t) end	
    return rhs!
end
```
```
keys = prognostic_vars(model)
    if length(keys) == 0
        return ClimaCore.Fields.FieldVector(; model_name => FT[])
else...
```

because we're only working with models that have prognostic variables...

**Comment by jb-mackay** [comment]
Some of these functions just define the interface, so it's not necessary to write tests for them imo. 

Since the above comments, `initialize_vars` was defined which is tested in setups with no aux variables.

I'm going to close this, we can open new issues if there are specific parts of the code that need testing.

**Comment by kmdeck** [comment]
thanks @jb-mackay !
