### ISSUE TITLE
Revisit the default "initialize" methods, what a domain is, where coordinates are stored

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#3]
The current implementation of `initialize` obtains coordinates for the domain, then creates an empty state vector, and an empty aux vector. The expectation is that the user would then populate these using the coordinates and their own initial condition functions. The user never fiddles with the structure of the state. It's always packaged in the same way.

Is there a better way to create Y from the domain? ClimaAtmos has something similar in spirit but a bit different:
https://github.com/CliMA/ClimaAtmos.jl/blob/ec56b8453712bff8e8662030993af3ec89b8b582/src/Models/Nonhydrostatic3DModels/nonhydrostatic_3d_model.jl#L44

We won't have face variables ever, and most model variables are not ClimaCore Fields. But it is nice that different variables for the same model are not required to have the same type - though it is not yet clear if we need that use case. Our current default assumes all variables for a model have the same type.

Are all variables tied to coordinates?

**Comment by kmdeck** [comment]
Decision to move `z` out of soil_aux as it is not an "updated" variable in the same as as e.g. temperature will be. If aux is initialized to an empty structure, with the expectation that `update_aux` will initialize it correctly, aux.soil.z will never get set. since `z` doesnt quite fit in, stick it in the model for now & revisit.

**Comment by kmdeck** [comment]
Revisit if "domain" is what we really want to store in Model. e.g. for soil, we use it to create the coordinates, but then it is never used by the RHS.

**Comment by kmdeck** [comment]
we can make the default give the variable a default type and initialize to that type, not just always call similar(coords).
https://github.com/CliMA/ClimaAtmos.jl/blob/ec56b8453712bff8e8662030993af3ec89b8b582/src/Models/Nonhydrostatic3DModels/nonhydrostatic_3d_model.jl#L44

^^ though that is fairly opaque to read

**Comment by kmdeck** [comment]
@jb-mackay's branch bm/initilize addresses these questions & can close this issue or make it more specific.

**Comment by jb-mackay** [comment]
Notes from earlier pair program with @kmdeck:

1. Introduce a `Point` domain so that we can always call `coodinates(model)`: coordinates(`Point`) -> [z_sfc]  (resolved by #28)
- ClimaLSM.Domains.coordinates(model::PondModel{FT, DomainType{FT}}) where {FT} = FT.([0.0])

2. Build two domain constructors for 3D/2D (box) and 2D/1D (column)
- 3D Extruded FD  for soil (N elements) + Extruded (1 element)
-  level(soil_space, 1) -> gives 2d space (then make ExtrudedFD space with this horizontal space, but with 1 element so we can call column)
- 1D Column for soil (N elements) (pure FD space) + Point domain
- specify different variable types that live at the point: scalar, static arrays
