### ISSUE TITLE
Revisit need for spherical shell domains

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLSM.jl#93]
Land surface models have a very large aspect ratio, so there is no real need for a spherical shell domain. 

Currently, it may be nice to have for coupled simulations if the lower atmos boundary space and upper land boundary space need to match. In the long run, they do not need to match, so we may be able to remove the spherical shell domain for LSMs.

@LenkaNovak do the boundary spaces for land and atmos need to match for AMIP? either way is fine! we have the spherical shell domain ready to merge if it is needed.

**Comment by LenkaNovak** [comment]
@kmdeck We can do both, but if the boundary spaces are not the same, we would have to use remapping and (at the moment with serial regridding) that would make the high-res AMIP sim significantly slower, especially since we're coupling at every timestep. If the boundary spaces are the same, we can use the same MPI distribution for atmos and land. It's good to start thinking about different spaces though for experiments beyond this first AMIP version. :)

**Comment by kmdeck** [comment]
ok! That's good to know. It makes sense then for us to have this capability! I will merge the PR adding it in. then we should be ready to try the enhanced bucket model coupled with atmos!
